//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstMatricula
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inasistencia
    {
        public int InasistenciaId { get; set; }
        public int MatriculaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual Matricula Matricula { get; set; }
    }
}
